### ISSUE TITLE
Fix this please

### ISSUE THREAD

**Issue by BlawoHD** [giantquartz-plugin-collection/SkyBlock#27]
![66f2cde6-01cd-4324-bcf4-eb9855c64812](https://user-images.githubusercontent.com/22114921/31194276-f0452d96-a946-11e7-9618-d1a0df37c846.jpeg)

**Comment by GiantQuartz** [comment]
Are you using the official software or a spoon?
It says it's a recursive dependency, have you installed all PMMP dependencies?

**Comment by Baducai** [comment]
i use PocketMine-MP

**Comment by armagadon159753** [comment]
I m use PMMP and the  plugin work fine

**Comment by BlawoHD** [comment]
PocketMine-MP Crash Dump Wed Oct 4 20:46:13 UTC 2017

Error: Nesting level too deep - recursive dependency?
File: SkyBlock - v0.1.8/src/SkyBlock/island/Island
Line: 264
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SkyBlock v0.1.8

Code:
[255]         $this->generator = $generator;
[256]     }
[257] 
[258]     /**
[259]      * Tries to remove a player
[260]      *
[261]      * @param Player $player
[262]      */
[263]     public function tryRemovePlayer(Player $player) {
[264]         if(in_array($player, $this->playersOnline)) {
[265]             unset($this->playersOnline[array_search($player, $this->playersOnline)]);
[266]         }
[267]     }
[268] 
[269]     /**
[270]      * Remove member
[271]      *
[272]      * @param string $string
[273]      */
[274]     public function removeMember($string) {

Backtrace:

PocketMine-MP version: 1.7dev #123 [Protocol 137; API 3.0.0-ALPHA9]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux vps 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64
PHP Version: 7.2.0RC2
Zend version: 3.2.0-dev
OS : Linux, linux

**Comment by GiantQuartz** [comment]
How can we reproduce this issue? @BlawoHD

**Comment by BlawoHD** [comment]
Shall I tell you the steps you can make a mistake?

**Comment by GiantQuartz** [comment]
Yup @BlawoHD

**Comment by majovec** [comment]
@GiantQuartz all software is spoom genisyspro pmmp turanic is spoom official software is dead

**Comment by BlawoHD** [comment]
Why closed?

**Comment by GiantQuartz** [comment]
@BlawoHD You didn't tell me the steps to reproduce the issue, also it doesn't seem to be a internal mistake, it seems like you need to install some missing dependencies.
