### ISSUE TITLE
/sb expel doesn't work as intended

### ISSUE THREAD

**Issue by XDqrkneZ** [giantquartz-plugin-collection/SkyBlock#28]
/sb expel a member from your island
player who got expelled(kick) from the island got teleported to spawn but can still go /sb join and edit, etc.
The player who got expelled also still in the /sb members list.

**Comment by GiantQuartz** [comment]
Is this still a thing? @XDqrkneZ

**Comment by XDqrkneZ** [comment]
sure

**Comment by GiantQuartz** [comment]
@XDqrkneZ **expel** is intended to kick a player from your island level, not from your team. To remove someone from your team you can use **remove**. I probably didn't explain this correctly!
