### ISSUE TITLE
Invite player bug

### ISSUE THREAD

**Issue by SuperAdam47** [giantquartz-plugin-collection/SkyBlock#29]
![screenshot_20171016-191555](https://user-images.githubusercontent.com/16169771/31623925-b3869888-b2a9-11e7-9f93-774be68b697e.png)

**Comment by SuperAdam47** [comment]
@GiantQuartz

**Comment by GiantQuartz** [comment]
That plugin isn't the official version of SkyBlock, we do not bring support to modified versions.
