### ISSUE TITLE
/sb makeleader

### ISSUE THREAD

**Issue by optimusprime338** [giantquartz-plugin-collection/SkyBlock#31]
I have been trying to fix this but for some reason I am not able to do so!
1. Create island
2. invite someone and make him leader 
3. until server restarts new owner haves permission to access island
4. After restart new owner as well as old owner loose permission to edit island.
5. speaking from config files both old owner and new owner have there profile for same island number 
![image](https://user-images.githubusercontent.com/27479208/34642209-57bd0bd2-f335-11e7-9be1-87082db357e7.png)
Well after successful transfer of leader it should delete old owner profile at instance but its not doing do for some reason!
Can you fix it . If can that will be awesome!
Thank you..

**Comment by xXNiceAssasinl0** [comment]
I even got this bug too

**Comment by GiantQuartz** [comment]
I found the problem, I'll do a commit fixing it soon

**Comment by xXNiceAssasinl0** [comment]
Thx

**Comment by TDMidkwhatisxd** [comment]
its been 16 hours xd
