### ISSUE TITLE
Unlimited Worlds glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [giantquartz-plugin-collection/SkyBlock#32]
/sb reset gives u a new island  .... that is ok .. it will be a hell to reset big chunks.....

But the old worlds get saved, and a player can make xxxxxxxx worlds ;---;  ....

Reseting every 5 minutes = a new world every 5 minutes ...

**Comment by 95CivicSi** [comment]
This problem is resolved in PR #41 and PR #43
