### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by DrakerZR** [giantquartz-plugin-collection/SkyBlock#37]
Hi. When I start My server, appears an erro,r: "ParseError: " syntax error, unexpected 'else' (T_ELSE)" (EXEPTION) in SkyBlock.phar/scr/SkyBlock/command/SkyBlockCommand" at line 125"
Help :cry:

**Comment by GiantQuartz** [comment]
Did you modify the plugin?

**Comment by GiantQuartz** [comment]
@DrakerZR Probably you did something wrong. I'm Spanish, so I probably can help you. DM me on twitter! @GiantQuartz

**Comment by DrakerZR** [comment]
Sure! Thank you
