### ISSUE TITLE
Unhandled exception executing command 'sb home' in skyblock

### ISSUE THREAD

**Issue by ver24436** [giantquartz-plugin-collection/SkyBlock#38]
**- Expected result: What were you expecting to happen?**

To be able to teleport to my custom set skyblock home using : 
` /sb home` 

**- Actual result: What actually happened?**

Received the following error message in client chat:
> An unknown error occurred while attempting to perform this command

### Steps to reproduce the issue

1. Join Server with Skyblock v0.1.9 plugin.
2. Do `/sb create` and do `/sb join`
3. Move to a new locations and set home with `/sb sethome`
4. After seeing the following message: 
> - You set your island home successfully!

Try to teleport to newly set Home using `/sb home`

Receive the following Error in client chat
> An unknown error occurred while attempting to perform this command

### OS and versions

**OS:** Microsoft Windows 10 Pro 64Bit
Version 1709 (OS Build 16299.309)

**PocketMine-MP:** 1.7dev-866 「[REDACTED]」 implementing API version 3.0.0-ALPHA11 for Minecraft: PE v1.2.10 (protocol version 201)

**Plugins:** DevTolls v1.12.9, Skyblock v0.1.9

====================================

Server Console Output- https://pastebin.com/9aAUPinc

**Comment by ver24436** [comment]
I wanted to pass along this solutions that @CortexPE and @KielKing came up with. Thanks guys!

Change the following in _\src\SkyBlock\Utils.php - line 62_

_**From**_
`return new Position($array[1], $array[2], $array[3], $level);`

**_To_**
`return new Position($array[1] + 0.11, $array[2] + 0.11, $array[3] + 0.11, $level);`

**Comment by GiantQuartz** [comment]
I'd rather go with [array_map()](http://php.net/manual/en/function.array-map.php)
