### ISSUE TITLE
can't break everything

### ISSUE THREAD

**Issue by isoz** [giantquartz-plugin-collection/SkyBlock#44]
Players claim to not be able to break certain blocks on the island, tried myself and one of the sides is unbreakable unless i'm OP.

Also on a side note some people don't always get a chest in their island.

**Comment by GiantQuartz** [comment]
Thanks for the heads up, @isoz. 
I tried to reproduce this issue with the latest version but nothing is coming up, did you try to disable spawn protection? (as @SuperAdam47 said)

**Comment by isoz** [comment]
I did, unfortunately that did not help.
